
package at.aau.ds.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculationService", targetNamespace = "http://ds.aau.at/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculationService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://ds.aau.at/", className = "at.aau.ds.service.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://ds.aau.at/", className = "at.aau.ds.service.AddResponse")
    @Action(input = "http://ds.aau.at/CalculationService/addRequest", output = "http://ds.aau.at/CalculationService/addResponse")
    public double add(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "divide", targetNamespace = "http://ds.aau.at/", className = "at.aau.ds.service.Divide")
    @ResponseWrapper(localName = "divideResponse", targetNamespace = "http://ds.aau.at/", className = "at.aau.ds.service.DivideResponse")
    @Action(input = "http://ds.aau.at/CalculationService/divideRequest", output = "http://ds.aau.at/CalculationService/divideResponse")
    public double divide(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiply", targetNamespace = "http://ds.aau.at/", className = "at.aau.ds.service.Multiply")
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://ds.aau.at/", className = "at.aau.ds.service.MultiplyResponse")
    @Action(input = "http://ds.aau.at/CalculationService/multiplyRequest", output = "http://ds.aau.at/CalculationService/multiplyResponse")
    public double multiply(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "subtract", targetNamespace = "http://ds.aau.at/", className = "at.aau.ds.service.Subtract")
    @ResponseWrapper(localName = "subtractResponse", targetNamespace = "http://ds.aau.at/", className = "at.aau.ds.service.SubtractResponse")
    @Action(input = "http://ds.aau.at/CalculationService/subtractRequest", output = "http://ds.aau.at/CalculationService/subtractResponse")
    public double subtract(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

}
